name: tango
description: flutter configuration tool.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  #https://pub.dev/packages/image
  image: ^2.1.12

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0
  mockito: ^4.1.1
